# Generated by Django 2.1.7 on 2019-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
