# Generated by Django 2.1.7 on 2019-06-24 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_auto_20190623_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='skater',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.Category'),
        ),
    ]
