# Generated by Django 2.1.7 on 2019-06-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_auto_20190624_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='world_standing',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
