# Generated by Django 2.1.7 on 2019-06-25 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_competitor_world_standing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignmentForEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.CategoryClass')),
                ('competitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.Competitor')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.Event')),
            ],
        ),
    ]
