# Generated by Django 2.1.7 on 2019-06-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_auto_20190626_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.Competitor')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.Event')),
            ],
        ),
    ]
